### ISSUE TITLE
Single-head or multi-head?

### ISSUE THREAD

**Issue by patronum08** [LeapLabTHU/MLLA#2]
Thank you for your work, which has inspired me greatly. 

In your paper, you mention that Mamba is a single-head model (Equation 12). This seems to differ from my understanding. You also state that Mamba applies Equation 9 to each channel (if Mamba's hidden size is D, then there should be E*D channels), implying that there is a distinct recurrent computation for each channel. If we unfold this, it can be seen as having ED different attention matrices. My understanding of a single-head model is that it has only one attention matrix. Therefore, can Mamba be considered as a structure with ED heads? I would appreciate your clarification on this matter.

**Comment by tian-qing001** [comment]
Hi @patronum08, thanks for your insightful question.

**Mamba can be viewed as a single-head model.** 

Equation 10 and Equation 11 of our paper are _exactly the selective SSM employed in Mamba_, which demonstrate that Mamba resembles a single-head model. While the original Mamba formula seems to adopt a multi-head design, our analysis in Section 3.2 (below Equation 8) shows that $\overline{B}_ix_i$ in Mamba is equivalent to to $\overline{B}_ix_i=B_i (\Delta_i\odot x_i)$. For a $C$ dimension input $x_i\in\mathbb{R}^{1\times C}$, the dimensions of $\overline{B}_i,B_i,\Delta_i$ are $\overline{B}_i\in\mathbb{R}^{d\times C},B_i\in\mathbb{R}^{d\times 1},\Delta_i\in\mathbb{R}^{1\times C}$, respectively. Given that we already interpret $\Delta_i\in\mathbb{R}^{1\times C}$ as an input gate, $B_i\in\mathbb{R}^{d\times 1}$ now resembles single-head attention, rather than multi-head design $\overline{B}_i\in\mathbb{R}^{d\times C}$.

**Comment by tian-qing001** [comment]
The Preliminaries section of our paper introduces some modifications to the formula formats of Mamba and linear attention. These modifications are important for understanding our analysis~

**Comment by patronum08** [comment]
Hi tian-qing,

Thank you for your response. I apologize for only seeing it now. 

I believe we need to clarify what a "head" is. In the context of transformers, a head can be represented by an attention matrix. If we extend this concept to Mamba and unroll equation 10, writing it as y = Mx, where M is composed of elements A, B, C, etc., the size of M is not seq_len * seq_len. This indicates that Mamba is not a single-head mechanism.

**Comment by tian-qing001** [comment]
Hi @patronum08, I believe our definition of "head" is consistent.

As I clarified above, in equation 10 of our paper, the original $\overline{B}_i\in\mathbb{R}^{d\times C}$ in Mamba paper is transformed into $\overline{B}_ix_i=B_i(\Delta_ix_i)$, where $B_i\in\mathbb{R}^{d\times 1},\Delta_i\in\mathbb{R}^{1\times C},x_i\in\mathbb{R}^{1\times C}$. This modification is discussed in Section 3.2.

We view $\Delta_i\in\mathbb{R}^{1\times C}$ as an input gate, and the ture input after this gate is $x'_i=\Delta_ix_i$. On this basis, if we unroll equation 10, it will be seen that $y_i=Mx'_i$, where $M$ is an equivalent single-head attention matrix.

**Comment by tian-qing001** [comment]
In addition, equation 11 and equation 12 directly reveal that Mamba resembles a variant of single-head linear attention. Notably, we do not claim Mamba itself is single-head attention. Instead, we believe that if we remove all other special designs, selective SSM will become single-head linear attention.

**Comment by patronum08** [comment]
Thank you for your response. I will delve deeper into understanding this issue. 

Additionally, it would be appreciated if you could provide the matrix representation of $M$ in your paper or code repository.
